server:
  port: 9010

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://postgresql-1.cfh61qv9x1da.us-west-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunckSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  # Security OAuth
  security:
    oauth2.client:
        registration:
          google:
            client-id: 911159205305-k6fo1s8niakigudu5pk78pk99ikh6jfe.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

jwt.secret: ''

# 토근 관련 secret Key 및 RedirectUrl 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/redirect




jwt:
  secret:
    key: 'fsdfsdrSerTStWQrEWHGISfsadfsdqwreeWRTEWtWetTEWSyRYdYdruhS324523GFDRTDRGAWQerrerfsdfsdfsdgdsgsdftgsdgsdg32fdsFGsdfsDfSDF'


logging:
  level:
    com:
      zaxxer:
        hikari: off
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      result: off

      result-settable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sql only: off     #SQL만 로그로 남긴다.
      sliding: debug    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: TRACE